import streamlit as st
from langchain_core.messages import HumanMessage

# Import your compiled graph from your agent module
from agent.graph import agent as compiled_graph

# Configure the Streamlit page
st.set_page_config(page_title="DevTeam AI", page_icon="👨‍💻", layout="centered")

st.title("👨‍💻 AI DevTeam Group Chat")
st.markdown("Chat with the **Planner**, **Architect**, and **Coder** to build your project!")

# 1. Initialize chat history in Streamlit session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# Define avatars for our agents
AVATARS = {
    "user": "👤",
    "planner": "🧠",
    "architect": "📐",
    "coder": "💻"
}

# 2. Display previous chat messages from history on app rerun
for msg in st.session_state.chat_history:
    with st.chat_message(msg["role"], avatar=AVATARS.get(msg["role"], "🤖")):
        st.markdown(msg["content"])

# 3. Handle User Input
if prompt := st.chat_input("What project should we build today? (e.g., A colorful modern todo app in HTML/CSS/JS)"):
    
    # Add user message to UI and history
    with st.chat_message("user", avatar=AVATARS["user"]):
        st.markdown(prompt)
    st.session_state.chat_history.append({"role": "user", "content": prompt})

    # Prepare the initial state for the LangGraph
    # Based on your graph, it expects a "user_prompt" key to start.
    inputs = {"user_prompt": prompt}
    config = {"recursion_limit": 100} # Keep your original recursion limit

    # 4. Stream the LangGraph execution
    with st.spinner("The team is assembling..."):
        
        # compiled_graph.stream yields a dictionary with the node name as the key
        for output in compiled_graph.stream(inputs, config):
            for node_name, state_update in output.items():
                
                # Check if this node returned a "messages" list (which we added in Phase 2)
                if "messages" in state_update and state_update["messages"]:
                    # Grab the latest message generated by this node
                    latest_msg = state_update["messages"][-1].content
                    
                    # Ensure node_name matches our avatar keys (lowercase)
                    role = node_name.lower()
                    
                    # Display the agent's message in the UI dynamically
                    with st.chat_message(role, avatar=AVATARS.get(role, "🤖")):
                        st.markdown(f"**{role.capitalize()}**\n\n{latest_msg}")
                    
                    # Save this agent's response to the session history
                    st.session_state.chat_history.append({
                        "role": role, 
                        "content": latest_msg
                    })